### ISSUE TITLE
Fluids render on top of all blocks

### ISSUE THREAD

**Issue by thegail** [stackotter/delta-client#22] opened 2021-10-11 05:08 UTC
**Describe the bug**
Fluids and stained glass panes render on top of all blocks, even when they are obstructed by those blocks

**To Reproduce**
Open a world with a fluid or stained glass pane obstructed by an opaque block. The fluid is still visible.

**Expected behavior**
The fluid or stained glass pane should be hidden where obscured by an opaque block.

**Screenshots**

![Screen Shot 2021-10-10 at 10 08 09 PM](https://user-images.githubusercontent.com/52760728/136736245-29779fef-ab4b-4d38-8b1a-21fbe9d8f3e4.png)

**Extra information**
- OS: macOS 11.3.1 Big Sur
- Hardware: 2020 M1 MacBook Air
- Build: Configuration release at f49536f463fc78a3c00edaade4cdc5f34e12c386

**Comment by stackotter** [comment] 2021-10-19 11:04
I can't reproduce this in the latest version, if you can still reproduce this please reopen the issue (or get me to if you can't, dunno how this works)

**Comment by stackotter** [comment] 2021-11-01 05:30
Resolved by @JezewskiG (#40)

**Closed by stackotter** 2021-11-01 05:30 UTC
Labels: bug
