### ISSUE TITLE
Joining server stuk at loading screen

### ISSUE THREAD

**Issue by ProfRedRooster** [stackotter/delta-client#71] opened 2021-12-31 20:17 UTC
**Describe the bug**
Joining server stuk at loading screen

**To Reproduce**
join a 1.16.2 server

**Expected behavior**
just join

**Screenshots**
<img width="911" alt="Schermafbeelding 2021-12-31 om 21 16 38" src="https://user-images.githubusercontent.com/52485505/147838059-d90d5bc4-5962-49f8-a980-b563e7a793ea.png">

**Extra information (please complete the following information**
-Mac OS 11.2.3
- intel MacBook Pro
- Build Version 0.1.0 (9)

> 31-12-2021 21:22:39.9060 n/a [info ] Loading plugins
> 31-12-2021 21:22:39.9170 n/a [info ] Loading registries
> 31-12-2021 21:22:39.9170 n/a [info ] Loading cached block registry
> 31-12-2021 21:22:40.1710 n/a [info ] Loading cached biome registry
> 31-12-2021 21:22:40.1760 n/a [info ] Loading cached fluid registry
> 31-12-2021 21:22:40.1770 n/a [info ] Loading cached entity registry
> 31-12-2021 21:22:40.1820 n/a [info ] Loading resource pack
> 31-12-2021 21:22:40.1830 n/a [debug] Loading resources from 'realms' namespace
> 31-12-2021 21:22:40.1830 n/a [debug] Loading textures
> 31-12-2021 21:22:40.1830 n/a [debug] Loading biome colors
> 31-12-2021 21:22:40.1840 n/a [debug] Loading cached block models
> 31-12-2021 21:22:40.1850 n/a [debug] Loading resources from 'minecraft' namespace
> 31-12-2021 21:22:40.1850 n/a [debug] Loading textures
> 31-12-2021 21:22:40.5150 n/a [debug] Loading biome colors
> 31-12-2021 21:22:40.5230 n/a [debug] Loading cached block models
> 31-12-2021 21:22:41.1500 n/a [info ] Done (1471.18ms)
> 31-12-2021 21:22:41.1800 n/a [error] @ SocketLayer.swift:166:handleNWError(_:), Connection refused: '127.0.0.1:25565'
> 31-12-2021 21:22:41.7680 n/a [debug] Packet received, id=0x00
> 31-12-2021 21:22:41.7690 n/a [debug] Received ping response from play.hypixel.net:25565
> 31-12-2021 21:22:41.8040 n/a [debug] Packet received, id=0x00
> 31-12-2021 21:22:41.8040 n/a [debug] Received ping response from play.kings-craft.com:25565
> 31-12-2021 21:22:50.6790 n/a [debug] Packet received, id=0x03
> 31-12-2021 21:22:50.6790 n/a [debug] Packet received, id=0x02
> 31-12-2021 21:22:50.6810 n/a [debug] Packet received, id=0x18
> 31-12-2021 21:22:50.6810 n/a [debug] plugin message received with channel: minecraft:register
> 31-12-2021 21:22:50.7630 n/a [debug] Packet received, id=0x25
> 31-12-2021 21:22:50.7640 n/a [debug] Packet received, id=0x18
> 31-12-2021 21:22:50.7640 n/a [debug] plugin message received with channel: minecraft:brand
> 31-12-2021 21:22:50.7640 n/a [debug] Packet received, id=0x18
> 31-12-2021 21:22:50.7640 n/a [debug] plugin message received with channel: minecraft:register
> 31-12-2021 21:22:50.7640 n/a [debug] Packet received, id=0x18
> 31-12-2021 21:22:50.7640 n/a [debug] plugin message received with channel: minecraft:brand
> 31-12-2021 21:22:50.7640 n/a [debug] Packet received, id=0x0d
> 31-12-2021 21:22:50.7640 n/a [debug] Packet received, id=0x31
> 31-12-2021 21:22:50.7640 n/a [debug] Packet received, id=0x3f
> 
>

**Comment by ProfRedRooster** [comment] 2021-12-31 20:18
Version 0.1.0 (8) works for me

**Comment by stackotter** [comment] 2022-01-01 02:16
Probably a duplicate of #67. It is not reproducible on my device. What macOS version are you on?

**Comment by ninjadev64** [comment] 2022-01-01 05:47
This is an exact duplicate of #67.

**Closed** 2022-01-01 05:48 UTC
Labels: bug
