### ISSUE TITLE
Stuck at "Pinging…" while trying to join a server or "Establishing connection…" in direct connect

### ISSUE THREAD

**Issue by MoustacheOff** [stackotter/delta-client#114] opened 2022-06-22 11:22 UTC
**Describe the bug**
After adding a server, the connection is stuck to "Pinging…" (or "Establishing connection…" in direct connect mode), so I'm unable to join any server (including the official test server).

**To Reproduce**
1. Add a server
2. Click "Save"
3. Select a server
or
1. Click the "direct connect" icon
2. Type in the server address
3. Click "Connect"

**Expected behavior**
According to the README.md, the client is supposed to display the MOTD of the server, the number of players online and the "Join" button.

**Screenshots**
![image](https://user-images.githubusercontent.com/49116367/175016071-bc8ed182-fe00-43e8-8443-4449bc9a137f.png)
![image](https://user-images.githubusercontent.com/49116367/175016650-2fff2915-d6e4-4c1a-9f18-03ecf024b0ec.png)

**Extra information (please complete the following information**
- OS: macOS 12.4
- Hardware: M1 Mac mini
- Build: `commit`[`0b76c80`](https://github.com/stackotter/delta-client/commit/0b76c80bc92f075e55c09dae550d006e2d175d0c)

**Additional context**
/

**Comment by stackotter** [comment] 2022-06-22 12:04
Seems like a duplicate of #67, although it's interesting that you're on Monterey. This issue has only be reported on Big Sur so far. Lets continue this conversation on #67.

**Closed by stackotter** 2022-06-22 12:04 UTC
Labels: bug

**Comment by MoustacheOff** [comment] 2022-06-22 12:45
> Oh yeah true, @MoustacheOff are you using restricted/proxied internet?

I don't think so…
"Normal" Minecraft works fine for me.

**Comment by MoustacheOff** [comment] 2022-06-22 12:46
Oh wait, it works! I was using cellular connection with my phone. After trying on Wi-Fi, it now works.
