### ISSUE TITLE
invalidSkyLightMask

### ISSUE THREAD

**Issue by ProfRedRooster** [stackotter/delta-client#73] opened 2022-01-01 14:08 UTC
**Describe the bug**

**To Reproduce**
join with a offline account a offline server(mc.herobrine.org:25565 maybe more)

**Expected behavior**
just join
**Screenshots**
![image](https://user-images.githubusercontent.com/52485505/147852355-7f74b179-1fa2-480a-bec9-4400cd152e91.png)

**Extra information (please complete the following information**
- Mac OS 12.1
- Intel MacBook Pro 2018
-  6838c9a dev build

**Comment by stackotter** [comment] 2022-01-01 21:16
Duplicate of #58

**Closed by stackotter** 2022-01-01 21:16 UTC
Labels: bug
