### ISSUE TITLE
Issues with Inventory (Failed to handle packet with id 0x16:)

### ISSUE THREAD

**Issue by OpenSource03** [stackotter/delta-client#119] opened 2022-08-30 20:08 UTC
**Describe the bug**
```
Failed to handle packet with id 0x16:
invalidInventorySlotindex9, window: 0)
```

**To Reproduce**
This error happens each time I try to join literally any server, such as CubeCraft.

**Expected behavior**
I expect the client to work without any issues on modern servers built for latest MC versions, such as CubeCraft. This issue seems to be related to inventory rendering.

**Screenshots**
![Screenshot 2022-08-30 at 22 08 17](https://user-images.githubusercontent.com/29690431/187533220-c76932dd-7701-4e05-8173-2eadf535a76b.png)

**Extra information (please complete the following information**
- OS: macOS 13 (Ventura) beta... I forgot, but it's the latest as of today :P
- Hardware: Mac Studio (M1 Max)
- Build: https://github.com/stackotter/delta-client/actions/runs/2954508562

**Comment by OpenSource03** [comment] 2022-08-30 20:12
Oh, it seems like there's different error based on server (dependant on which version the server is based on). Below one is from Hypixel (which is 1.8 based), but it's very similar to the CubeCraft error above (which happens on all 1.19 based servers)

![Screenshot 2022-08-30 at 22 08 45](https://user-images.githubusercontent.com/29690431/187533308-1b6d9d19-e626-4e6b-8ef8-f74b8374296f.png)

**Comment by ninjadev64** [comment] 2022-08-30 20:18
Does this behaviour occur when using a 1.16.1 server (e.g. `play.stackotter.dev`)?

**Comment by stackotter** [comment] 2022-08-30 21:41
@OpenSource03 thanks for reporting this! It seems to be an issue with the networking code related to inventories. Currently the `text-rendering` branch is a work in progress so it's not very optimised and probably has quite a few bugs. Until I fix this, using a build from the `main` branch should fix your issues (although `main` also has issues on Hypixel). Alternatively you can try our official test server which should hopefully work, but of course isn't as cool as joining proper public servers.

**Comment by OpenSource03** [comment] 2022-08-30 21:50
> Does this behaviour occur when using a 1.16.1 server (e.g. `play.stackotter.dev`)?

Works only on that server :P

> @OpenSource03 thanks for reporting this! It seems to be an issue with the networking code related to inventories. Currently the `text-rendering` branch is a work in progress so it's not very optimised and probably has quite a few bugs. Until I fix this, using a build from the `main` branch should fix your issues (although `main` also has issues on Hypixel). Alternatively you can try our official test server which should hopefully work, but of course isn't as cool as joining proper public servers.

I see, alright. It seems to be working specifically and only on the test server. I wanted to checkout the latest one just to see if Inventory is finally there. It's amazing to see the progress, even if it comes only in a form of bottom toolbar. I'm so excited to see this one day fully released 🤩.

**Comment by ninjadev64** [comment] 2022-08-30 21:53
The test server is just a vanilla 1.16.1 server so it should work on any servers with that version.

**Comment by stackotter** [comment] 2022-08-30 21:57
> It's amazing to see the progress, even if it comes only in a form of bottom toolbar. I'm so excited to see this one day fully released 🤩.

Thanks! There are a few more difficult problems to solve and then hopefully I'll be able to make a lot of progress in terms of the GUI and world interaction :)

**Comment by stackotter** [comment] 2022-09-06 11:55
The inventory packet error should be fixed now

**Comment by stackotter** [comment] 2022-09-06 22:59
And now I've fixed world rendering on Hypixel, there was an infinite loop caused by two arguments being the wrong way around :( that took quite a while to find.

If either of these issues persists feel free to reopen the issue

**Closed by stackotter** 2022-09-06 22:59 UTC
Labels: bug
